# Generated by Codex on 2026-05-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_done_status(apps, schema_editor):
    Todo = apps.get_model("tasks", "Todo")
    Todo.objects.filter(completed=True).update(status="done")


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_todo_due_date_todo_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("color", models.CharField(default="#2563eb", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="todo",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="todo",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="reminder_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                default="backlog",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="todos",
                to="tasks.project",
            ),
        ),
        migrations.CreateModel(
            name="Subtask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("todo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subtasks", to="tasks.todo")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["position", "-created_at"]},
        ),
        migrations.RunPython(backfill_done_status, migrations.RunPython.noop),
    ]
